name: go-test
on:
  push:
    branches:
      - main
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: false

      - name: Run Tests
        run: go test ./... -v
