name: go-test
on:
  push:
  pull_request:
jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23
          cache: false
      - name: go-test
        run: go test ./... -v
